// Finally Clause
const f=()=>{

    try {
        let a = 0
        // console.log(progam)
        console.log("program run successfully")
        return a
    } catch (error) {
        console.log("This is an error")
        console.log(p)
    }
    finally{
        console.log("I am Not bay ")
        // Close the File 
        // Exit the loop
        // Write to the log file
    }
}

f()